name: Run setup script
on:
  push:
    branches:
      - main

jobs:
  run_setup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run setup script
        run: |
          chmod +x ./Linux/setup_hw1.sh
          ./Linux/setup_hw1.sh https://github.com/NYUAppSec/appsec_hw1.git test@example.com "Test User" test_gpg_id
          cd ./appsec_hw1/
          gcc giftcardreader.c -o giftcardreader
          make test
          