name: Run setup script on Ubuntu hw2
on:
  push:
    branches:
      - main

jobs:
  run_setup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup script
        run: |
          sudo apt install git
          git clone https://github.com/NYUAppSec/appsec_hw2.git
          chmod +x ./Linux/setup_hw2.sh
          ./Linux/setup_hw2.sh ./appsec_hw2

