name: Run setup script hw1 ubuntu
on:
  push:
    branches:
      - main

jobs:
  run_setup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run setup script
        run: |
          chmod +x ./Linux/setup_hw1.sh
          ./Linux/setup_hw1.sh


          